apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: memory-game-app
  namespace: default
spec:
  destination:
    namespace: memory-game
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: ./
    repoURL: https://github.com/ilya-redkin/argocdmanifest
    targetRevision: main
  # syncPolicy: 
  #   automated:
  #     prune: true
  #     selfHeal: false
  #   syncOptions:
  #   - CreateNamespace=true