---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: memory-game
  name: memory-game
  namespace: memory-game
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: memory-game